name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: Build React App
        run: CI=false npm run build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build tiny-animation.surge.sh --token ${{secrets.SURGE_TOKEN}}
